/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Label;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextField;


public class frmParqueadero extends javax.swing.JFrame {

    /**
     * Creates new form Parqueadero
     */
    public frmParqueadero() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parqueadero2 = new javax.swing.JTextField();
        parqueadero1 = new javax.swing.JTextField();
        parqueadero3 = new javax.swing.JTextField();
        parqueadero4 = new javax.swing.JTextField();
        parqueadero5 = new javax.swing.JTextField();
        parqueadero6 = new javax.swing.JTextField();
        parqueadero7 = new javax.swing.JTextField();
        parqueadero8 = new javax.swing.JTextField();
        parqueadero9 = new javax.swing.JTextField();
        parqueadero10 = new javax.swing.JTextField();
        parqueadero11 = new javax.swing.JTextField();
        parqueadero12 = new javax.swing.JTextField();
        lblHora = new javax.swing.JLabel();
        parqueadero13 = new javax.swing.JTextField();
        parqueadero14 = new javax.swing.JTextField();
        parqueadero15 = new javax.swing.JTextField();
        parqueadero16 = new javax.swing.JTextField();
        parqueadero17 = new javax.swing.JTextField();
        parqueadero18 = new javax.swing.JTextField();
        parqueadero19 = new javax.swing.JTextField();
        parqueadero20 = new javax.swing.JTextField();
        btnSalir = new javax.swing.JButton();
        btnIngresar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnMovimientos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblValor = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEstado = new javax.swing.JLabel();
        txtPuestosVacios = new javax.swing.JTextField();
        txtValorCaja1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        parqueadero2.setText("    2");
        getContentPane().add(parqueadero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 40, 30));

        parqueadero1.setText("    1");
        getContentPane().add(parqueadero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 30));

        parqueadero3.setText("    3");
        getContentPane().add(parqueadero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 30));

        parqueadero4.setText("    4");
        getContentPane().add(parqueadero4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 40, 30));

        parqueadero5.setText("    5");
        getContentPane().add(parqueadero5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 40, 30));

        parqueadero6.setText("    6");
        getContentPane().add(parqueadero6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 40, 30));

        parqueadero7.setText("    7");
        getContentPane().add(parqueadero7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 40, 30));

        parqueadero8.setText("    8");
        getContentPane().add(parqueadero8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 40, 30));

        parqueadero9.setText("    9");
        getContentPane().add(parqueadero9, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 40, 40, 30));

        parqueadero10.setText("   10");
        getContentPane().add(parqueadero10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 40, 30));

        parqueadero11.setText("   11");
        getContentPane().add(parqueadero11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 40, 30));

        parqueadero12.setText("   12");
        getContentPane().add(parqueadero12, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 40, 30));
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 90, 30));

        parqueadero13.setText("   13");
        getContentPane().add(parqueadero13, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 40, 30));

        parqueadero14.setText("   14");
        getContentPane().add(parqueadero14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 40, 30));

        parqueadero15.setText("   15");
        getContentPane().add(parqueadero15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 40, 30));

        parqueadero16.setText("   16");
        getContentPane().add(parqueadero16, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 40, 30));

        parqueadero17.setText("   17");
        getContentPane().add(parqueadero17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 40, 30));

        parqueadero18.setText("   18");
        getContentPane().add(parqueadero18, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 40, 30));

        parqueadero19.setText("   19");
        getContentPane().add(parqueadero19, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 40, 30));

        parqueadero20.setText("   20");
        getContentPane().add(parqueadero20, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 40, 30));

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnSalir.setText("SALIR");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 30));

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIngresar.setText("INGRESAR");
        getContentPane().add(btnIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, 30));

        btnModificar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnModificar.setText("MODIFICAR");
        getContentPane().add(btnModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 30));

        btnMovimientos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnMovimientos.setText("MOVIMIENTOS");
        getContentPane().add(btnMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("PUESTOS VACIOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, -1, -1));

        lblValor.setText(" ");
        getContentPane().add(lblValor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 100, -1));

        jLabel3.setText("INFORMACIÓN");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));

        lblEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblEstado.setText(" ");
        getContentPane().add(lblEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, -1, -1));
        getContentPane().add(txtPuestosVacios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 180, 30));
        getContentPane().add(txtValorCaja1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 180, 30));

        jLabel5.setText(" ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 80, 10, -1));

        jLabel6.setText(" ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 10, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("VALOR EN CAJA: ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, -1, -1));

        jLabel4.setText("PARQUEADERO VALOR HORA: $");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JLabel getLblHora() {
        return lblHora;
    }

    public void setLblHora(JLabel lblHora) {
        this.lblHora = lblHora;
    }

    public JTextField getParqueadero1() {
        return parqueadero1;
    }

    public void setParqueadero1(JTextField parqueadero1) {
        this.parqueadero1 = parqueadero1;
    }

    public JTextField getParqueadero10() {
        return parqueadero10;
    }

    public void setParqueadero10(JTextField parqueadero10) {
        this.parqueadero10 = parqueadero10;
    }

    public JTextField getParqueadero11() {
        return parqueadero11;
    }

    public void setParqueadero11(JTextField parqueadero11) {
        this.parqueadero11 = parqueadero11;
    }

    public JTextField getParqueadero12() {
        return parqueadero12;
    }

    public void setParqueadero12(JTextField parqueadero12) {
        this.parqueadero12 = parqueadero12;
    }

    public JTextField getParqueadero13() {
        return parqueadero13;
    }

    public void setParqueadero13(JTextField parqueadero13) {
        this.parqueadero13 = parqueadero13;
    }

    public JTextField getParqueadero14() {
        return parqueadero14;
    }

    public void setParqueadero14(JTextField parqueadero14) {
        this.parqueadero14 = parqueadero14;
    }

    public JTextField getParqueadero15() {
        return parqueadero15;
    }

    public void setParqueadero15(JTextField parqueadero15) {
        this.parqueadero15 = parqueadero15;
    }

    public JTextField getParqueadero16() {
        return parqueadero16;
    }

    public void setParqueadero16(JTextField parqueadero16) {
        this.parqueadero16 = parqueadero16;
    }

    public JTextField getParqueadero17() {
        return parqueadero17;
    }

    public void setParqueadero17(JTextField parqueadero17) {
        this.parqueadero17 = parqueadero17;
    }

    public JTextField getParqueadero18() {
        return parqueadero18;
    }

    public void setParqueadero18(JTextField parqueadero18) {
        this.parqueadero18 = parqueadero18;
    }

    public JTextField getParqueadero19() {
        return parqueadero19;
    }

    public void setParqueadero19(JTextField parqueadero19) {
        this.parqueadero19 = parqueadero19;
    }

    public JTextField getParqueadero2() {
        return parqueadero2;
    }

    public void setParqueadero2(JTextField parqueadero2) {
        this.parqueadero2 = parqueadero2;
    }

    public JTextField getParqueadero20() {
        return parqueadero20;
    }

    public void setParqueadero20(JTextField parqueadero20) {
        this.parqueadero20 = parqueadero20;
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }

    public void setBtnIngresar(JButton btnIngresar) {
        this.btnIngresar = btnIngresar;
    }

    public JButton getBtnModificar() {
        return btnModificar;
    }

    public void setBtnModificar(JButton btnModificar) {
        this.btnModificar = btnModificar;
    }

    public JButton getBtnMovimientos() {
        return btnMovimientos;
    }

    public void setBtnMovimientos(JButton btnMovimientos) {
        this.btnMovimientos = btnMovimientos;
    }

    public JLabel getLblValor() {
        return lblValor;
    }

    public void setLblValor(JLabel lblValor) {
        this.lblValor = lblValor;
    }

    

    public JButton getBtnSalir() {
        return btnSalir;
    }

    public void setBtnSalir(JButton btnSalir) {
        this.btnSalir = btnSalir;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public void setjLabel1(JLabel jLabel1) {
        this.jLabel1 = jLabel1;
    }

    public JLabel getjLabel2() {
        return lblValor;
    }

    public void setjLabel2(JLabel jLabel2) {
        this.lblValor = jLabel2;
    }

    public JLabel getjLabel3() {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3) {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4() {
        return lblEstado;
    }

    public void setjLabel4(JLabel jLabel4) {
        this.lblEstado = jLabel4;
    }


    public JTextField getTxtPuestosVacios() {
        return txtPuestosVacios;
    }

    public void setTxtPuestosVacios(JTextField txtPuestosVacios) {
        this.txtPuestosVacios = txtPuestosVacios;
    }

    public JLabel getLblEstado() {
        return lblEstado;
    }

    public void setLblEstado(JLabel lblEstado) {
        this.lblEstado = lblEstado;
    }

    public JTextField getTxtValorCaja1() {
        return txtValorCaja1;
    }

    public void setTxtValorCaja1(JTextField txtValorCaja1) {
        this.txtValorCaja1 = txtValorCaja1;
    }

    

    public JTextField getParqueadero3() {
        return parqueadero3;
    }

    public void setParqueadero3(JTextField parqueadero3) {
        this.parqueadero3 = parqueadero3;
    }

    public JTextField getParqueadero4() {
        return parqueadero4;
    }

    public void setParqueadero4(JTextField parqueadero4) {
        this.parqueadero4 = parqueadero4;
    }

    public JTextField getParqueadero5() {
        return parqueadero5;
    }

    public void setParqueadero5(JTextField parqueadero5) {
        this.parqueadero5 = parqueadero5;
    }

    public JTextField getParqueadero6() {
        return parqueadero6;
    }

    public void setParqueadero6(JTextField parqueadero6) {
        this.parqueadero6 = parqueadero6;
    }

    public JTextField getParqueadero7() {
        return parqueadero7;
    }

    public void setParqueadero7(JTextField parqueadero7) {
        this.parqueadero7 = parqueadero7;
    }

    public JTextField getParqueadero8() {
        return parqueadero8;
    }

    public void setParqueadero8(JTextField parqueadero8) {
        this.parqueadero8 = parqueadero8;
    }

    public JTextField getParqueadero9() {
        return parqueadero9;
    }

    /**
     * @param args the command line arguments
     */
    public void setParqueadero9(JTextField parqueadero9) {
        this.parqueadero9 = parqueadero9;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnMovimientos;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblEstado;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblValor;
    private javax.swing.JTextField parqueadero1;
    private javax.swing.JTextField parqueadero10;
    private javax.swing.JTextField parqueadero11;
    private javax.swing.JTextField parqueadero12;
    private javax.swing.JTextField parqueadero13;
    private javax.swing.JTextField parqueadero14;
    private javax.swing.JTextField parqueadero15;
    private javax.swing.JTextField parqueadero16;
    private javax.swing.JTextField parqueadero17;
    private javax.swing.JTextField parqueadero18;
    private javax.swing.JTextField parqueadero19;
    private javax.swing.JTextField parqueadero2;
    private javax.swing.JTextField parqueadero20;
    private javax.swing.JTextField parqueadero3;
    private javax.swing.JTextField parqueadero4;
    private javax.swing.JTextField parqueadero5;
    private javax.swing.JTextField parqueadero6;
    private javax.swing.JTextField parqueadero7;
    private javax.swing.JTextField parqueadero8;
    private javax.swing.JTextField parqueadero9;
    private javax.swing.JTextField txtPuestosVacios;
    private javax.swing.JTextField txtValorCaja1;
    // End of variables declaration//GEN-END:variables
}
